
CFG_HI_CHIP_TYPE=hi3798cv200

CFG_HI_SMMU_SUPPORT=y

CFG_HI_PROC_SUPPORT=y

CFG_LIB_JPEG_VERSION_6B=y
CFG_LIB_PNG_VERSION_1_4_16=y
CFG_HI_JPEG6B_STREAMBUFFER_SIZE=0x100000

# CFG_HI_MSP_BUILDIN is not set

CFG_HI_PLAYER_FULL_SUPPORT=y
