
#===============================================================================
# local variable
#===============================================================================
HIGO_DIR := $(shell pwd)


HEADER_FILES += $(HIGO_DIR)/include/hi_go_surface.h
HEADER_FILES += $(HIGO_DIR)/include/hi_go_errno.h
HEADER_FILES += $(HIGO_DIR)/include/hi_go_comm.h

#===============================================================================
# rules
#===============================================================================


all:
	$(AT)cp -rf $(HEADER_FILES) $(INCLUDE_DIR)/

