#=======================================
#	local variable
#=======================================

objects := mali700

objects_clean	    := ${addsuffix _clean,${objects}}
objects_install	    := ${addsuffix _install,${objects}}
objects_uninstall   := ${addsuffix _uninstall,${objects}}

EXTRA_CFLAGS := -Werror

obj-y += $(objects)/
