//******************************************************************************
//  Copyright (C), 2007-2014, Hisilicon Technologies Co., Ltd.
//
//******************************************************************************
// File name     : Reg_HEVC_H264.h
// Version       : 2.0
// Author        : l00214825
// Created       : 2014-10-28
// Last Modified : 
// Description   :  逻辑寄存器结构体
// Function List : 
// History       : 
// 1 Date        : 
// Author        : xxx
// Modification  : Create file
//******************************************************************************
#include "./inc_96mv200/cabac_reg.h"
#include "./inc_96mv200/curld_reg.h"
#include "./inc_96mv200/dblk_reg.h"
#include "./inc_96mv200/emar_reg.h"
#include "./inc_96mv200/fme_reg.h"
#include "./inc_96mv200/ime_reg.h"
#include "./inc_96mv200/func_reg.h"
#include "./inc_96mv200/intra_reg.h"
#include "./inc_96mv200/mrg_reg.h"
#include "./inc_96mv200/nbi_reg.h"
#include "./inc_96mv200/pack_reg.h"
#include "./inc_96mv200/pmeld_reg.h"
#include "./inc_96mv200/pintra_reg.h"
#include "./inc_96mv200/pmeinfo_ld_reg.h"
#include "./inc_96mv200/pmeinfo_st_reg.h"
#include "./inc_96mv200/pmest_reg.h"
#include "./inc_96mv200/pme_reg.h"
#include "./inc_96mv200/pmv_reg.h"
#include "./inc_96mv200/qpg_reg.h"
#include "./inc_96mv200/qpgld_reg.h"
#include "./inc_96mv200/recst_reg.h"
#include "./inc_96mv200/refld_reg.h"
#include "./inc_96mv200/sao_reg.h"
#include "./inc_96mv200/sel_reg.h"
#include "./inc_96mv200/tqitq_reg.h"
#include "./inc_96mv200/vcpi_reg.h"
#include "./inc_96mv200/vctrl_reg.h"
#include "./inc_96mv200/vlcst_reg.h"
#include "./inc_96mv200/vlc_reg.h"
#include "./inc_96mv200/vedu_reg.h"
#include "./inc_96mv200/mmu_reg.h"

#ifndef __C_UNION_DEFINE_VEDU_REG_H__
#define __C_UNION_DEFINE_VEDU_REG_H__

/*-------------- Vcpi start  0x20620000 ---------------------*/ 

typedef struct
{ 
	
    /* Vcpi寄存器结构体   0x20620000  */
    volatile S_vedu_REGS_TYPE   VEDU_REGS;
	
    /* func寄存器结构体   0x20620000  */
    volatile S_func_REGS_TYPE   VEDU_FUNC_REGS;

    /* Vcpi寄存器结构体   0x20620000  */
    volatile S_vcpi_REGS_TYPE   VEDU_VCPI_REGS;
    
    /* Vctrl寄存器结构体   0x20620200  */
    volatile S_vctrl_REGS_TYPE  VEDU_VCTRL_REGS;

   /* Refid寄存器结构体   0x20620800  */
    volatile S_qpgld_REGS_TYPE VEDU_QPGLD_REGS;
    
    /* Curld寄存器结构体   0x20620400  */
    volatile S_curld_REGS_TYPE  VEDU_CURLD_REGS;

	/* nbi 寄存器结构体   0x20622200  */
	volatile S_nbi_REGS_TYPE  VEDU_NBI_REGS;

  	/* pmeld 寄存器结构体   0x20622c00  */
    volatile S_pmeld_REGS_TYPE  VEDU_PMELD_REGS;  

	/* pmeinfold 寄存器结构体   0x20622c00  */
    volatile S_pmeinfo_ld_REGS_TYPE  VEDU_PMEINFO_LD_REGS;  
	
    /* Pme寄存器结构体    0x20620600  */
    volatile S_pme_REGS_TYPE  VEDU_PME_REGS;

    /* pmest 寄存器结构体   0x20622e00  */       
      volatile S_pmest_REGS_TYPE  VEDU_PMEST_REGS;

    /* pmeinfost 寄存器结构体   0x20622c00  */
      volatile S_pmeinfo_st_REGS_TYPE  VEDU_PMEINFO_ST_REGS;

    /* Qpg寄存器结构体   0x20620c00  */
    volatile S_qpg_REGS_TYPE VEDU_QPG_REGS;
	
    /* Refid寄存器结构体   0x20620800  */
    volatile S_refld_REGS_TYPE VEDU_REFLD_REGS;

 /* Intra寄存器结构体   0x20621200  */
    volatile S_pintra_REGS_TYPE VEDU_PINTRA_REGS;

    /* Ime寄存器结构体   0x20620a00  */
    volatile S_ime_REGS_TYPE VEDU_IME_REGS;
	
    /* Fme寄存器结构体   0x20621000  */
    volatile S_fme_REGS_TYPE VEDU_FME_REGS;
	
    /* Mrg寄存器结构体   0x20620e00  */
    volatile S_mrg_REGS_TYPE VEDU_MRG_REGS;
    
    /* Intra寄存器结构体   0x20621200  */
    volatile S_intra_REGS_TYPE VEDU_INTRA_REGS;
    
    /* Pmv寄存器结构体   0x20621400  */
    volatile S_pmv_REGS_TYPE VEDU_PMV_REGS;

    /* tqitq寄存器结构体   0x20622600  */
    volatile S_tqitq_REGS_TYPE VEDU_TQITQ_REGS; 

    /* sel寄存器结构体   0x20621600  */
	volatile S_sel_REGS_TYPE  VEDU_SEL_REGS;     
       
    /*  Dblk寄存器结构体   0x20621800  */
       volatile S_dblk_REGS_TYPE  VEDU_DBLK_REGS;   
          
    /*  Sao寄存器结构体   0x20621a00  */
     volatile S_sao_REGS_TYPE  VEDU_SAO_REGS;

    /* recst 保留 0x20622a00  */
     volatile S_recst_REGS_TYPE  VEDU_RECST_REGS;
		 
    /* Pack寄存器结构体   0x20621c00  */
 	volatile S_pack_REGS_TYPE  VEDU_PACK_REGS; 
    
    /* Cabac寄存器结构体   0x20621e00  */
    volatile S_cabac_REGS_TYPE  VEDU_CABAC_REGS;    
      
    /* vlc寄存器结构体   0x20622000  */
     volatile S_vlc_REGS_TYPE  VEDU_VLC_REGS;

    /* vlcst 寄存器结构体   0x20622400  */ 
	volatile S_vlcst_REGS_TYPE  VEDU_VLCST_REGS;
	
	/* emar寄存器结构体   0x20620000  */
    volatile S_emar_REGS_TYPE   VEDU_EMAR_REGS;
	
	/* mmu 寄存器结构体   0x2062f000 */
	volatile S_mmu_REGS_TYPE   VEDU_MMU_REGS;  
	

}S_VEDU_REGS_TYPE;


typedef struct
{
    HI_U32 CABAC_GLB_CFG;
    HI_U32 CABAC_SLCHDR_SIZE;
    HI_U32 CABAC_SLCHDR_PART1;
    HI_U32 CABAC_SLCHDR_PART2_SEG1;

    HI_U32 CABAC_SLCHDR_PART2_SEG2;
    HI_U32 CABAC_SLCHDR_PART2_SEG3;
    HI_U32 CABAC_SLCHDR_PART2_SEG4;
    HI_U32 CABAC_SLCHDR_PART2_SEG5;

    HI_U32 CABAC_SLCHDR_PART2_SEG6;
    HI_U32 CABAC_SLCHDR_PART2_SEG7;
    HI_U32 CABAC_SLCHDR_PART2_SEG8;
    HI_U32 CABAC_SLCHDR_SIZE_I;

    HI_U32 CABAC_SLCHDR_PART1_I;
    HI_U32 CABAC_SLCHDR_PART2_SEG1_I;
    HI_U32 CABAC_SLCHDR_PART2_SEG2_I;
    HI_U32 CABAC_SLCHDR_PART2_SEG3_I;

    HI_U32 CABAC_SLCHDR_PART2_SEG4_I;
    HI_U32 CABAC_SLCHDR_PART2_SEG5_I;
    HI_U32 CABAC_SLCHDR_PART2_SEG6_I;
    HI_U32 CABAC_SLCHDR_PART2_SEG7_I;

    HI_U32 CABAC_SLCHDR_PART2_SEG8_I;
    HI_U32 reserved[11];
}S_CABAC_SLICE_HEAD_TYPE;

typedef struct
{
    HI_U32 VLC_SLCHDRSTRM0;
    HI_U32 VLC_SLCHDRSTRM1;
    HI_U32 VLC_SLCHDRSTRM2;
    HI_U32 VLC_SLCHDRSTRM3;
	
    HI_U32 VLC_REORDERSTRM0;
    HI_U32 VLC_REORDERSTRM1;
    HI_U32 VLC_MARKINGSTRM0;
    HI_U32 VLC_MARKINGSTRM1;
	
    HI_U32 VLC_SLCHDRPARA;
    HI_U32 VLC_SVC;
    HI_U32 VLC_SLCHDRSTRM0_I;
    HI_U32 VLC_SLCHDRSTRM1_I;
	
    HI_U32 VLC_SLCHDRSTRM2_I;
    HI_U32 VLC_SLCHDRSTRM3_I;
    HI_U32 VLC_REORDERSTRM0_I;
    HI_U32 VLC_REORDERSTRM1_I;
	
    HI_U32 VLC_MARKINGSTRM0_I;
    HI_U32 VLC_MARKINGSTRM1_I;
    HI_U32 VLC_SLCHDRPARA_I;
    HI_U32 reserved[13];
}S_VLC_SLICE_HEAD_TYPE;

typedef union
{
    S_CABAC_SLICE_HEAD_TYPE  CABAC_SLICE_HEAD;
    S_VLC_SLICE_HEAD_TYPE    VLC_SLICE_HEAD;
} U_SLICE_HEAD_TYPE;

typedef struct
{

   HI_U32    VEDU_VCPI_TILE_SIZE;
   HI_U32    VEDU_VCPI_PICSIZE_PIX;
   HI_U32    VEDU_VCPI_MULTISLC;
   HI_U32    VEDU_VCPI_QPCFG;
   HI_U32    VEDU_VCPI_DBLKCFG;
   HI_U32    VEDU_VCPI_TMV_LOAD;
   HI_U32    VEDU_VCPI_CROSS_TILE_SLC;
   HI_U32    VEDU_VCPI_INTRA_INTER_CU_EN;
   HI_U32    VEDU_VCPI_VLC_CONFIG;
   HI_U32    VEDU_VCPI_PRE_JUDGE_EXT_EN;
   HI_U32    VEDU_VCPI_PRE_JUDGE_COST_THR;
   HI_U32    VEDU_VCPI_IBLK_PRE_MV_THR;
   HI_U32    VEDU_VCPI_PME_PARAM;
   HI_U32    VEDU_VCPI_PIC_STRONG_EN;
   HI_U32    VEDU_VCPI_REF_FLAG;
   HI_U32    VEDU_VCPI_RC_ENABLE;
   HI_U32    VEDU_VCPI_I_SLC_INSERT;
   HI_U32    VEDU_VCPI_CLKDIV_ENABLE;
   HI_U32    VEDU_VCPI_WCHN_BYPASS;
   HI_U32    VEDU_VCPI_RCHN_BYPASS;
   HI_U32    VEDU_VCPI_SW_L0_SIZE;
   HI_U32    VEDU_VCPI_SW_L1_SIZE;
   HI_U32    VEDU_VCPI_PMEINFO_ST_ADDR;
   HI_U32    VEDU_VCPI_PMEINFO_LD0_ADDR;
   HI_U32    VEDU_VCPI_PMEINFO_LD1_ADDR;
   HI_U32    VEDU_VCPI_TUNLCELL_ADDR;
   HI_U32    VEDU_VCPI_SRC_YADDR;
   HI_U32    VEDU_VCPI_SRC_CADDR;
   HI_U32    VEDU_VCPI_SRC_VADDR;
   HI_U32    VEDU_VCPI_YH_ADDR;
   HI_U32    VEDU_VCPI_CH_ADDR;
   HI_U32    VEDU_VCPI_STRIDE;
   HI_U32    VEDU_VCPI_REC_YADDR;
   HI_U32    VEDU_VCPI_REC_CADDR;
   HI_U32    VEDU_VCPI_REC_STRIDE;
   HI_U32    VEDU_VCPI_REC_YH_ADDR;
   HI_U32    VEDU_VCPI_REC_CH_ADDR;
   HI_U32    VEDU_VCPI_REC_HEAD_STRIDE;
   HI_U32    VEDU_VCPI_REFY_L0_ADDR;
   HI_U32    VEDU_VCPI_REFC_L0_ADDR;
   HI_U32    VEDU_VCPI_REF_L0_STRIDE;
   HI_U32    VEDU_VCPI_REFYH_L0_ADDR;
   HI_U32    VEDU_VCPI_REFCH_L0_ADDR;
   HI_U32    VEDU_VCPI_REFH_L0_STRIDE;
   HI_U32    VEDU_VCPI_PMELD_L0_ADDR;
   HI_U32    VEDU_VCPI_REFY_L1_ADDR;
   HI_U32    VEDU_VCPI_REFC_L1_ADDR;
   HI_U32    VEDU_VCPI_REF_L1_STRIDE;
   HI_U32    VEDU_VCPI_REFYH_L1_ADDR;
   HI_U32    VEDU_VCPI_REFCH_L1_ADDR;
   HI_U32    VEDU_VCPI_REFH_L1_STRIDE;
   HI_U32    VEDU_VCPI_PMELD_L1_ADDR;
   HI_U32    VEDU_VCPI_PMEST_ADDR;
   HI_U32    VEDU_VCPI_NBI_UPST_ADDR;
   HI_U32    VEDU_VCPI_NBI_MVST_ADDR;
   HI_U32    VEDU_VCPI_NBI_MVLD_ADDR;
   HI_U32    VEDU_VCPI_STRMADDR;
   HI_U32    VEDU_VCPI_SWPTRADDR;
   HI_U32    VEDU_VCPI_SRPTRADDR;
   HI_U32    VEDU_VCPI_STRFMT;
   HI_U32    VEDU_VCPI_PMEST_STRIDE;
   HI_U32    VEDU_VCPI_PMELD_STRIDE;
   HI_U32    reserved1[2];
   HI_U32    VEDU_VCTRL_ROI_CFG0;
   HI_U32    VEDU_VCTRL_ROI_CFG1;
   HI_U32    VEDU_VCTRL_ROI_CFG2;
   HI_U32    VEDU_VCTRL_ROI_SIZE_0;
   HI_U32    VEDU_VCTRL_ROI_SIZE_1;
   HI_U32    VEDU_VCTRL_ROI_SIZE_2;
   HI_U32    VEDU_VCTRL_ROI_SIZE_3;
   HI_U32    VEDU_VCTRL_ROI_SIZE_4;
   HI_U32    VEDU_VCTRL_ROI_SIZE_5;
   HI_U32    VEDU_VCTRL_ROI_SIZE_6;
   HI_U32    VEDU_VCTRL_ROI_SIZE_7;
   HI_U32    VEDU_VCTRL_ROI_START_0;
   HI_U32    VEDU_VCTRL_ROI_START_1;
   HI_U32    VEDU_VCTRL_ROI_START_2;
   HI_U32    VEDU_VCTRL_ROI_START_3;
   HI_U32    VEDU_VCTRL_ROI_START_4;
   HI_U32    VEDU_VCTRL_ROI_START_5;
   HI_U32    VEDU_VCTRL_ROI_START_6;
   HI_U32    VEDU_VCTRL_ROI_START_7;
   HI_U32    VEDU_VCTRL_NORM_TR16X16_COEFF_DENOISE;
   HI_U32    VEDU_VCTRL_NORM_COEFF_DENOISE;
   HI_U32    VEDU_VCTRL_NORM_ENG_DENOISE;
   HI_U32    VEDU_VCTRL_SKIN_TR16X16_COEFF_DENOISE;
   HI_U32    VEDU_VCTRL_SKIN_COEFF_DENOISE;
   HI_U32    VEDU_VCTRL_SKIN_ENG_DENOISE;
   HI_U32    VEDU_VCTRL_HEDGE_TR16X16_COEFF_DENOISE;
   HI_U32    VEDU_VCTRL_HEDGE_COEFF_DENOISE;
   HI_U32    VEDU_VCTRL_HEDGE_ENG_DENOISE;
   HI_U32    VEDU_VCTRL_HEDGEMOV_TR16X16_COEFF_DENOISE;
   HI_U32    VEDU_VCTRL_HEDGEMOV_COEFF_DENOISE;
   HI_U32    VEDU_VCTRL_HEDGEMOV_ENG_DENOISE;
   HI_U32    VEDU_VCTRL_STATIC_TR16X16_COEFF_DENOISE;
   HI_U32    VEDU_VCTRL_STATIC_COEFF_DENOISE;
   HI_U32    VEDU_VCTRL_STATIC_ENG_DENOISE;
   HI_U32    VEDU_VCTRL_SOBELSTR_TR16X16_COEFF_DENOISE;
   HI_U32    VEDU_VCTRL_SOBELSTR_COEFF_DENOISE;
   HI_U32    VEDU_VCTRL_SOBELSTR_ENG_DENOISE;
   HI_U32    VEDU_VCTRL_SOBELWEAK_TR16X16_COEFF_DENOISE;
   HI_U32    VEDU_VCTRL_SOBELWEAK_COEFF_DENOISE;
   HI_U32    VEDU_VCTRL_SOBELWEAK_ENG_DENOISE;
   HI_U32    VEDU_VCTRL_INTRA_RDO_FACTOR_0;
   HI_U32    VEDU_VCTRL_INTRA_RDO_FACTOR_1;
   HI_U32    VEDU_VCTRL_INTRA_RDO_FACTOR_2;
   HI_U32    VEDU_VCTRL_MRG_RDO_FACTOR_0;
   HI_U32    VEDU_VCTRL_MRG_RDO_FACTOR_1;
   HI_U32    VEDU_VCTRL_MRG_RDO_FACTOR_2;
   HI_U32    VEDU_VCTRL_FME_RDO_FACTOR_0;
   HI_U32    VEDU_VCTRL_FME_RDO_FACTOR_1;
   HI_U32    VEDU_VCTRL_FME_RDO_FACTOR_2;
   HI_U32    VEDU_VCTRL_SEL_INTRA_RDO_FACTOR;
   HI_U32    VEDU_VCTRL_SEL_INTER_RDO_FACTOR_0;
   HI_U32    VEDU_VCTRL_SEL_INTER_RDO_FACTOR_1;
   HI_U32    VEDU_VCTRL_SEL_INTER_RDO_FACTOR_2;
   HI_U32    VEDU_VCTRL_SEL_LAYER_RDO_FACTOR;
   HI_U32    reserved2[2];
   HI_U32    VEDU_CURLD_GCFG;
   HI_U32    VEDU_CURLD_CLIP_THR;
   HI_U32    VEDU_PME_SW_ADAPT_EN;
   HI_U32    VEDU_PME_SW_THR0;
   HI_U32    VEDU_PME_SW_THR1;
   HI_U32    VEDU_PME_SW_THR2;
   HI_U32    VEDU_PME_SKIP_PRE;
   HI_U32    VEDU_PME_TR_WEIGHTX;
   HI_U32    VEDU_PME_TR_WEIGHTY;
   HI_U32    VEDU_PME_SR_WEIGHT;
   HI_U32    VEDU_PME_INTRABLK_DET;
   HI_U32    VEDU_PME_INTRABLK_DET_THR;
   HI_U32    VEDU_PME_SKIN_THR;
   HI_U32    VEDU_PME_INTRA_LOWPOW;
   HI_U32    VEDU_PME_IBLK_COST_THR;
   HI_U32    VEDU_PME_STRONG_EDGE;
   HI_U32    VEDU_PME_LARGE_MOVE_THR;
   HI_U32    VEDU_PME_INTER_STRONG_EDGE;
   HI_U32    VEDU_PME_NEW_COST;
   HI_U32    VEDU_PME_WINDOW_SIZE0_L0;
   HI_U32    VEDU_PME_WINDOW_SIZE1_L0;
   HI_U32    VEDU_PME_WINDOW_SIZE2_L0;
   HI_U32    VEDU_PME_WINDOW_SIZE3_L0;
   HI_U32    VEDU_PME_COST_OFFSET;
   HI_U32    VEDU_PME_SAFE_CFG;
   HI_U32    VEDU_PME_IBLK_REFRESH;
   HI_U32    VEDU_PME_IBLK_REFRESH_NUM;
   HI_U32    VEDU_PME_QPG_RC_THR0;
   HI_U32    VEDU_PME_QPG_RC_THR1;
   HI_U32    VEDU_PME_LOW_LUMA_THR;
   HI_U32    VEDU_PME_PBLK_PRE1;
   HI_U32    VEDU_PME_CHROMA_FLAT;
   HI_U32    VEDU_PME_LUMA_FLAT;
   HI_U32    VEDU_PME_MADI_FLAT;
   HI_U32    reserved3[2];
   HI_U32    VEDU_QPG_MAX_MIN_QP;
   HI_U32    VEDU_QPG_ROW_TARGET_BITS;
   HI_U32    VEDU_QPG_AVERAGE_LCU_BITS;
   HI_U32    VEDU_QPG_LOWLUMA;
   HI_U32    VEDU_QPG_HEDGE;
   HI_U32    VEDU_QPG_HEDGE_MOVE;
   HI_U32    VEDU_QPG_LARGE_MOVE;
   HI_U32    VEDU_QPG_SKIN;
   HI_U32    VEDU_QPG_INTRA_DET;
   HI_U32    VEDU_QPG_H264_SMOOTH;
   HI_U32    VEDU_QPG_CU_QP_DELTA_THRESH_REG0;
   HI_U32    VEDU_QPG_CU_QP_DELTA_THRESH_REG1;
   HI_U32    VEDU_QPG_CU_QP_DELTA_THRESH_REG2;
   HI_U32    VEDU_QPG_CU_QP_DELTA_THRESH_REG3;
   HI_U32    VEDU_QPG_DELTA_LEVEL;
   HI_U32    VEDU_QPG_MADI_SWITCH_THR;
   HI_U32    VEDU_QPG_CU32_DELTA;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG00;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG01;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG02;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG03;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG04;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG05;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG06;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG07;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG08;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG09;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG10;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG11;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG12;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG13;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG14;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG15;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG16;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG17;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG18;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG19;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG20;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG21;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG22;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG23;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG24;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG25;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG26;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG27;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG28;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG29;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG30;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG31;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG32;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG33;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG34;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG35;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG36;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG37;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG38;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG39;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG40;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG41;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG42;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG43;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG44;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG45;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG46;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG47;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG48;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG49;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG50;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG51;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG52;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG53;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG54;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG55;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG56;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG57;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG58;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG59;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG60;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG61;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG62;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG63;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG64;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG65;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG66;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG67;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG68;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG69;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG70;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG71;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG72;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG73;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG74;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG75;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG76;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG77;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG78;
   HI_U32    VEDU_QPG_QP_LAMBDA_CTRL_REG79;
   HI_U32    VEDU_QPG_LAMBDA_MODE;
   HI_U32    VEDU_QPG_QP_RESTRAIN;
   HI_U32    VEDU_QPG_CU_MIN_SAD_THRESH_0;
   HI_U32    VEDU_QPG_CU_MIN_SAD_THRESH_1;
   HI_U32    VEDU_QPG_CU_MIN_SAD_REG;
   HI_U32    VEDU_QPG_FLAT_REGION;
   HI_U32    reserved4[1];
   HI_U32    VEDU_IME_INTER_MODE;
   HI_U32    VEDU_IME_RDOCFG;
   HI_U32    VEDU_IME_FME_LPOW_THR;
   HI_U32    VEDU_IME_NO_INTRA_ANG_EN;
   HI_U32    VEDU_IME_NO_INTRA_ANG_MV_THR;
   HI_U32    VEDU_MRG_FORCE_ZERO_EN;
   HI_U32    VEDU_MRG_FORCE_SKIP_EN;
   HI_U32    VEDU_INTRA_INTER_AVAIL;
   HI_U32    VEDU_INTRA_DC_SHIFT;
   HI_U32    VEDU_INTRA_BIT_WEIGHT;
   HI_U32    VEDU_INTRA_DC_MADI;
   HI_U32    VEDU_INTRA_RDO_COST_OFFSET;
   HI_U32    VEDU_INTRA_CHNL4_ANG_0EN;
   HI_U32    VEDU_INTRA_CHNL8_ANG_0EN;
   HI_U32    VEDU_INTRA_CHNL8_ANG_1EN;
   HI_U32    VEDU_INTRA_CHNL16_ANG_0EN;
   HI_U32    VEDU_INTRA_CHNL16_ANG_1EN;
   HI_U32    VEDU_INTRA_CHROMA_ANG_EN;
   HI_U32    VEDU_PMV_POC_0;
   HI_U32    VEDU_PMV_POC_1;
   HI_U32    VEDU_PMV_POC_2;
   HI_U32    VEDU_PMV_POC_3;
   HI_U32    VEDU_PMV_POC_4;
   HI_U32    VEDU_PMV_POC_5;
   HI_U32    VEDU_PMV_TMV_EN;
   HI_U32    VEDU_TQITQ_DEADZONE;
   HI_U32    VEDU_SEL_INTRA_ABS_OFFSET0;
   HI_U32    VEDU_SEL_INTRA_ABS_OFFSET1;
   HI_U32    VEDU_SEL_INTER_ABS_OFFSET0;
   HI_U32    VEDU_SEL_OFFSET_STRENGTH;
   HI_U32    VEDU_SEL_CU32_DC_AC_TH_OFFSET;
   HI_U32    VEDU_SEL_CU32_QP_TH;
   HI_U32    VEDU_SEL_RES_DC_AC_TH;
   HI_U32    VEDU_CABAC_GLB_CFG;
   HI_U32    VEDU_CABAC_SLCHDR_SIZE;
   HI_U32    VEDU_CABAC_SLCHDR_PART1;
   HI_U32    VEDU_CABAC_SLCHDR_PART2_SEG1;
   HI_U32    VEDU_CABAC_SLCHDR_PART2_SEG2;
   HI_U32    VEDU_CABAC_SLCHDR_PART2_SEG3;
   HI_U32    VEDU_CABAC_SLCHDR_PART2_SEG4;
   HI_U32    VEDU_CABAC_SLCHDR_PART2_SEG5;
   HI_U32    VEDU_CABAC_SLCHDR_PART2_SEG6;
   HI_U32    VEDU_CABAC_SLCHDR_PART2_SEG7;
   HI_U32    VEDU_CABAC_SLCHDR_PART2_SEG8;
   HI_U32    VEDU_CABAC_SLCHDR_SIZE_I;
   HI_U32    VEDU_CABAC_SLCHDR_PART1_I;
   HI_U32    VEDU_CABAC_SLCHDR_PART2_SEG1_I;
   HI_U32    VEDU_CABAC_SLCHDR_PART2_SEG2_I;
   HI_U32    VEDU_CABAC_SLCHDR_PART2_SEG3_I;
   HI_U32    VEDU_CABAC_SLCHDR_PART2_SEG4_I;
   HI_U32    VEDU_CABAC_SLCHDR_PART2_SEG5_I;
   HI_U32    VEDU_CABAC_SLCHDR_PART2_SEG6_I;
   HI_U32    VEDU_CABAC_SLCHDR_PART2_SEG7_I;
   HI_U32    VEDU_CABAC_SLCHDR_PART2_SEG8_I;
   HI_U32    VEDU_VLC_SLCHDRSTRM0;
   HI_U32    VEDU_VLC_SLCHDRSTRM1;
   HI_U32    VEDU_VLC_SLCHDRSTRM2;
   HI_U32    VEDU_VLC_SLCHDRSTRM3;
   HI_U32    VEDU_VLC_REORDERSTRM0;
   HI_U32    VEDU_VLC_REORDERSTRM1;
   HI_U32    VEDU_VLC_MARKINGSTRM0;
   HI_U32    VEDU_VLC_MARKINGSTRM1;
   HI_U32    VEDU_VLC_SLCHDRPARA;
   HI_U32    VEDU_VLC_SVC;
   HI_U32    VEDU_VLC_SLCHDRSTRM0_I;
   HI_U32    VEDU_VLC_SLCHDRSTRM1_I;
   HI_U32    VEDU_VLC_SLCHDRSTRM2_I;
   HI_U32    VEDU_VLC_SLCHDRSTRM3_I;
   HI_U32    VEDU_VLC_REORDERSTRM0_I;
   HI_U32    VEDU_VLC_REORDERSTRM1_I;
   HI_U32    VEDU_VLC_MARKINGSTRM0_I;
   HI_U32    VEDU_VLC_MARKINGSTRM1_I;
   HI_U32    VEDU_VLC_SLCHDRPARA_I;
   HI_U32    VEDU_VLCST_PTBITS_EN;
   HI_U32    VEDU_VLCST_PTBITS;
   HI_U32    VEDU_VLCST_STRMBUFLEN0;
   HI_U32    VEDU_VLCST_STRMBUFLEN1;
   HI_U32    VEDU_VLCST_STRMBUFLEN2;
   HI_U32    VEDU_VLCST_STRMBUFLEN3;
   HI_U32    VEDU_VLCST_STRMBUFLEN4;
   HI_U32    VEDU_VLCST_STRMBUFLEN5;
   HI_U32    VEDU_VLCST_STRMBUFLEN6;
   HI_U32    VEDU_VLCST_STRMBUFLEN7;
   HI_U32    VEDU_VLCST_STRMBUFLEN8;
   HI_U32    VEDU_VLCST_STRMBUFLEN9;
   HI_U32    VEDU_VLCST_STRMBUFLEN10;
   HI_U32    VEDU_VLCST_STRMBUFLEN11;
   HI_U32    VEDU_VLCST_STRMBUFLEN12;
   HI_U32    VEDU_VLCST_STRMBUFLEN13;
   HI_U32    VEDU_VLCST_STRMBUFLEN14;
   HI_U32    VEDU_VLCST_STRMBUFLEN15;
   HI_U32    VEDU_VLCST_STRMADDR0;
   HI_U32    VEDU_VLCST_STRMADDR1;
   HI_U32    VEDU_VLCST_STRMADDR2;
   HI_U32    VEDU_VLCST_STRMADDR3;
   HI_U32    VEDU_VLCST_STRMADDR4;
   HI_U32    VEDU_VLCST_STRMADDR5;
   HI_U32    VEDU_VLCST_STRMADDR6;
   HI_U32    VEDU_VLCST_STRMADDR7;
   HI_U32    VEDU_VLCST_STRMADDR8;
   HI_U32    VEDU_VLCST_STRMADDR9;
   HI_U32    VEDU_VLCST_STRMADDR10;
   HI_U32    VEDU_VLCST_STRMADDR11;
   HI_U32    VEDU_VLCST_STRMADDR12;
   HI_U32    VEDU_VLCST_STRMADDR13;
   HI_U32    VEDU_VLCST_STRMADDR14;
   HI_U32    VEDU_VLCST_STRMADDR15;
   HI_U32    VEDU_VLCST_PARA_ADDR;
   HI_U32    VEDU_VLCST_PARAMETER;
   HI_U32    VEDU_VLCST_PARA_DATA0;
   HI_U32    VEDU_VLCST_PARA_DATA1;
   HI_U32    VEDU_VLCST_PARA_DATA2;
   HI_U32    VEDU_VLCST_PARA_DATA3;
   HI_U32    VEDU_VLCST_PARA_DATA4;
   HI_U32    VEDU_VLCST_PARA_DATA5;
   HI_U32    VEDU_VLCST_PARA_DATA6;
   HI_U32    VEDU_VLCST_PARA_DATA7;
   HI_U32    VEDU_VLCST_PARA_DATA8;
   HI_U32    VEDU_VLCST_PARA_DATA9;
   HI_U32    VEDU_VLCST_PARA_DATA10;
   HI_U32    VEDU_VLCST_PARA_DATA11;
   HI_U32    VEDU_VLCST_PARA_DATA12;
   HI_U32    VEDU_VLCST_PARA_DATA13;
   HI_U32    VEDU_VLCST_PARA_DATA14;
   HI_U32    VEDU_VLCST_PARA_DATA15;
   HI_U32    VEDU_VLCST_PARA_DATA16;
   HI_U32    VEDU_VLCST_PARA_DATA17;
   HI_U32    VEDU_VLCST_PARA_DATA18;
   HI_U32    VEDU_VLCST_PARA_DATA19;
   HI_U32    VEDU_VLCST_PARA_DATA20;
   HI_U32    VEDU_VLCST_PARA_DATA21;
   HI_U32    VEDU_VLCST_PARA_DATA22;
   HI_U32    VEDU_VLCST_PARA_DATA23;
   HI_U32    VEDU_VLCST_PARA_DATA24;
   HI_U32    VEDU_VLCST_PARA_DATA25;
   HI_U32    VEDU_VLCST_PARA_DATA26;
   HI_U32    VEDU_VLCST_PARA_DATA27;
   HI_U32    VEDU_VLCST_PARA_DATA28;
   HI_U32    VEDU_VLCST_PARA_DATA29;
   HI_U32    VEDU_VLCST_PARA_DATA30;
   HI_U32    VEDU_VLCST_PARA_DATA31;
   HI_U32    VEDU_VLCST_PARA_DATA32;
   HI_U32    VEDU_VLCST_PARA_DATA33;
   HI_U32    VEDU_VLCST_PARA_DATA34;
   HI_U32    VEDU_VLCST_PARA_DATA35;
   HI_U32    VEDU_VLCST_PARA_DATA36;
   HI_U32    VEDU_VLCST_PARA_DATA37;
   HI_U32    VEDU_VLCST_PARA_DATA38;
   HI_U32    VEDU_VLCST_PARA_DATA39;
   HI_U32    VEDU_VLCST_PARA_DATA40;
   HI_U32    VEDU_VLCST_PARA_DATA41;
   HI_U32    VEDU_VLCST_PARA_DATA42;
   HI_U32    VEDU_VLCST_PARA_DATA43;
   HI_U32    VEDU_VLCST_PARA_DATA44;
   HI_U32    VEDU_VLCST_PARA_DATA45;
   HI_U32    VEDU_VLCST_PARA_DATA46;
   HI_U32    VEDU_VLCST_PARA_DATA47;
   HI_U32    VEDU_ENV_CHN;
   HI_U32    reserved5[2];

}S_HEVC_AVC_NODE_TYPE;


#endif /* __C_UNION_DEFINE_VCPI_H__ */

