
#obj-y += kapi/ misc/ soc/ clk/ atags/ flash_stats/

#obj-$(CONFIG_BLK_DEV_LOOP)		+= initfile/
#obj-$(CONFIG_VIRTUAL_INPUT)		+= vinput/
#obj-$(CONFIG_CMA)			+= cma/
#obj-$(CONFIG_USB_OTG_HISI)		+= usbotg/
#obj-$(CONFIG_REGULATOR)		+= regulator/
#obj-$(CONFIG_HASH_VRF_DEV)		+= hash_vrf_dev/
#obj-$(CONFIG_THERMAL)			+= thermal/
#obj-$(CONFIG_PCIE_HISILICON)		+= pcie/

obj-y += atags/
obj-y += kapi/
obj-y += hi_fence/
obj-y += misc/

obj-$(CONFIG_BLK_DEV_RAM) += initmrd/
obj-$(CONFIG_CMA) += cma/
