#=======================================
#	local variable
#======================================
objects := gpio pdm pq hdmi vo hifb tde jpeg png ddr
objects += i2c demux
objects += sync adsp aiao adec vpss mce
objects += jpge
objects += gfx2d
objects += pvr
objects += gpu
objects += hi_dbe
objects += keyled
objects += sci
objects += aenc
objects += base

obj-y += ${addsuffix /,${objects}}
