#=======================================
#	local variable
#======================================
#objects := gpio pdm pq hdmi vo hifb tde jpeg png ddr
#objects += i2c demux
#objects += sync adsp aiao adec vpss mce
#objects += jpge
#objects += gfx2d
#objects += pvr
#objects += gpu
#objects += hi_dbe
#objects += keyled
#objects += sci
#objects += aenc
#objects += base

objects := adec
objects += adsp
objects += aiao
objects += base
objects += gfx2d
objects += gpio
objects += gpu
objects += hdmi
objects += hi_dbe
objects += hifb
objects += mce
objects += omxvdec
objects += pdm
objects += pq
objects += pvr
objects += sync
objects += tde
objects += vdec
objects += vfmw
objects += vo
objects += vpss

obj-y += ${addsuffix /,${objects}}
