
#obj-$(CONFIG_TIMER_HISP804)		+= hisp804-timer.o
#obj-$(CONFIG_TIMER_HIFIXTIMER)		+= hifixtimer.o
obj-y					+= export_sym.o
#obj-$(CONFIG_HI_I2C)			+= i2c-hisi.o
#obj-$(CONFIG_HAVE_HW_BREAKPOINT)	+= hw_breakpoint.o
